### PR TITLE
Make `check` mutable in `TaskImpl` + add `task!()` macro

### PR DESCRIPTION
**Pull request by Atlinx**
Before I explain this PR I'd like to provide my reasoning of why behavior trees are so powerful.

# Why Behavior Trees?
After reading [Chris Simpson's article on Behavior Trees](https://www.gamedeveloper.com/programming/behavior-trees-for-ai-how-they-work), I've interpreted the nodes of behavior trees as "functions" that can have inputs and outputs. These inputs and outputs can then be stored and read from variables, to create more complex behavior. And so behavior trees become a powerful way to compose more complex behavior from simple parts. In a way, it's like programming AI behavior in your own AI programming language.

For example, consider the following tree:

```
                 Sequence
                     |
            .--------'--------.
            |        |        |
IsNear(out: Enemy)  Follow(Enemy)  Attack(Enemy)
```
In this diagram, `out: Variable` means the node has an output that is assigned to the given `Variable`. For example `isNear(out: Enemy)` assigns the nearest found enemy to the `Enemy` variable.

This behavior tree can be interpreted as the following pseudo-code
```python
  (enemy, result) = is_near()
  if result != Success: 
      return result
  result = follow(enemy)
  if result != Success: 
      return result
  attack(enemy)

def is_near(type):
    if an enemy is nearby:
        return (enemy, Fail)
    else:
        return (None, Success)

def follow(target):
    if target is within range:
        follow target
        if target is close enough to enemy:
            return Success
        else:
            return Running
    else:
        return Fail

def attack(target):
    if target is within range:
        attack target
        return Success
    else:
        return Fail
```

We can also make more complex nodes from existing nodes, similar to how we can make more complex functions using existing functions. For example, we can use the previous behavior tree example and name it a `ChaseAndAttackNearbyEnemies` node.
```
       ChaseAndAttackNearbyEnemies(out: Target)
                     |
                 Sequence
                     |
            .--------'--------.
            |        |        |
IsNear(out: Enemy)  Follow(Enemy)  Attack(Enemy)

                      ChaseAndAttackAndFreezeNearbyEnemies(out: Target)
                                       |
                                    Sequence
                                       |
                              .--------'-------.
                              |                |
ChaseAndAttackNearbyEnemies(out: Enemy)    Freeze(Enemy)
```

`ChaseAndAttacknearbyEnemies` can be represented by the following function, which returns the found nearby enemy as an output:
```python
def chase_and_attack_nearby_enemies():
  (enemy, result) = is_near()
  if result != Success: 
      return (enemy, result)
  result = follow(enemy)
  if result != Success: 
      return (enemy, result)
  result = attack(enemy)
  return (enemy, result)
```

# Implementing Input/Output Nodes in `bevior_tree`

With the previous paragraph explaining why nodes with inputs and outputs are useful, we can discuss how to implement these nodes within `bevior_tree`. In this PR, I slightly modified `chase.rs` example to illustrate the use of input/output nodes. In this example, there are multiple players and multiple enemies. Enemies should chase after the nearest player within a certain range around them.

Implementing inputs and outputs is simple, since for tasks,
- Inputs of type `T` can be represented by `Fn() -> Option<T>` parameters 

**Ex.**
```rust
impl FollowTask {
    pub fn new<F>(range: f32, speed: f32, target: F) -> Arc<Self>
    where
        F: Fn() -> Option<Entity> + Send + Sync + 'static,
    {
...
```
`FollowTask` has an input named `target`, with type `Option<Entity>`. The `target` is the entity that this task will attempt to chase after. You can call the `target` closure by running `(target)()` to get the current target that `FollowTask` should follow.

- Outputs can be represented by parameters of a custom output struct wrapped in an `Arc<Mutex<>>`

**Ex.**
```rust
pub struct NearTaskOutput {
    pub target: Option<Entity>,
}
impl NearTask {
    pub fn new(range: f32, output: Arc<Mutex<NearTaskOutput>>) -> Arc<Self> {
...
```

`NearTask` has an output named `target`, with type `Option<Entity>`. Other tasks can read from `NearTaskOutput.target` to find the nearest target entity selected by `NearTask`. You can write to the output by locking the mutex and then editing the output variable.

## The Problem

However, when we implement the `Follow` system to make the enemies move toward their target, how do we know what target the enemy is following? This information is stored within the `FollowTask` itself, and we'd need some way of moving this information into the `Follow` component of each enemy. This means `FollowTask` must mutate the `Follow` component attached to the entity it's running on. But since `TaskImpl::new(check)` expects `check` to be a read-only system, this is impossible

# The Solution

I propose we make `TaskImpl::new(check)` accept a regular `System`, to allow for mutations in the world, which allows "inputs" of a task to be processed by systems within the world.

I'm not completely familiar with how the `update` system is set up, but if the `update` system is set up to run on its own without any other systems running in parallel, then it should be safe to mutate the world within the `check` functions of each task. 

Please feel free to give feedback on my changes.

## Addendum

Since tasks seem to share a similar definition format I've also created a `task!()` macro in this PR, which reduces the boilerplate code needed to create a task.

**Original tasks definitions**
```rust
struct IsNearTask {
    task: Arc<TaskImpl>,
}
impl Task for IsNearTask {
    // Specify what checker you use with this task.
    fn task_impl(&self) -> Arc<TaskImpl> {
        self.task.clone()
    }
}

struct FollowTask {
    task: Arc<TaskImpl>,
}
impl Task for FollowTask {
    // Specify what checker you use with this task.
    fn task_impl(&self) -> Arc<TaskImpl> {
        self.task.clone()
    }
}
```

**Shortened task definitions using `task!()` macro**
```rust
task!(IsNearTask);
task!(FollowTask);
```

### CODE REVIEW

**Comment by hyranno** [comment]
I don't understand this PR for now, since the first commit is too big.
It seems to contain "core solution for the issue", "adding macro", "changes to the example" and "formatting".
These should be separate PRs, or at least separate commits.

The `chase.rs` is the simple example for beginners.
It also matches to the example of `seldom_state`.
So create another example (`chase_multiple.rs`) for your (relatively complex) situation.

`TaskImpl::on_enter`, `on_exit` is for mutating world.
You mean these are not sufficient?

**Comment by Atlinx** [comment]
Ok, I can move the `chase.rs` and `adding macros` to separate PRs then, since they're unrelated to this issue. 👍 

Regarding mutating the world within tasks, both `on_enter` and `on_exit` are insufficient because they provide a closure of `Fn(Entity, Commands)`. With `Commands`, you cannot mutate resources, mutate fields in components, etc. 

Given that the `check` function is parsed as a `System` function, that gives us access to `Query<>`, `Res<>` and other parameter types that give us access to various parts of the world. However since `check` is a read-only system, we can't use `Query<&mut ...>` or `ResMut<>` to mutate the world. 

Even if on_enter and on_exit are parsed as a `System` function, that still won't handle the case where a task needs to update a component with new data it just received after the task has already started, but before the task has exited.

**Comment by hyranno** [comment]
In `bevior_tree`, `Task` is not for real update (confusing name, indeed).
The behavior tree just decides what to do, then the other systems do real update later.
`Task` is kind of bridge between the behavior tree and other systems.
`Task` marks what to do for other systems (usually via adding component) and check the completion to proceed the behavior tree.
The `on_enter` and `on_exit` can be used to mark what to do.

In the `chase.rs` example, the `FollowTask` insert `Follow` component, then another system `follow` does actual update.
`NearTask` does not add any markers because no systems does update for it.

This pattern is needed to keep advantages of ECS.
ECS does good performance running same kind of tasks in a batch.
But while processing the behavior trees, various tasks appears in various order.
So the `Task` nodes just marks what to do, then other systems does actual updates later.

**Comment by Atlinx** [comment]
I see, I guess another option for passing data from the state machine is to put the Arc<Mutex<>> objects directly inside of the component that gets added during a state's runtime. This way data still can get passed into the state and used by systems acting upon the state.

**Pull request closed without merging**
